crm项目2/crm_poject/app01/urls.py
from django.conf.urls import url, include
from app01 import views
from app01.views import base, consultrecord, Customer, enrollment, user,teacher

urlpatterns = [
    # 登陆
    url('login/', user.login, name='login'),
    # 注册
    url('register/', user.register, name='register'),
    # 注册
    url(r'logout/', user.logout, name='logout'),
    # 客户展示
    url(r'index/', Customer.Customer.as_view(), name='index'),
    url(r'my_curtor/', Customer.Customer.as_view(), name='my_curtor'),
    # 客户添加和编辑
    url(r'curtor_add/$', Customer.add, name='curtoradd'),
    url(r'custoredit/(\d+)/', Customer.add, name='custoredit'),
    # 某个销售的跟进记录
    url(r'^consult_record/$', consultrecord.ConsultRecordList.as_view(), name='consult_record'),
    # 某个客户的跟进记录
    url(r'^consult_record/(?P<customer_id>\d+)/$', consultrecord.ConsultRecordList.as_view(),
        name='one_consult_record'),
    # 跟进记录添加和编辑
    url(r'^consult_record_add/$', consultrecord.consult_record_change, name='consult_record_add'),
    url(r'^consult_record_edit/(\d+)/$', consultrecord.consult_record_change, name='consult_record_edit'),
    # 显示报名表
    url(r'^enrollment_list/$', enrollment.EnrollmentList.as_view(), name='enrollment_list'),
    url(r'^enrollment_list/(?P<customer_id>\d+)/$', enrollment.EnrollmentList.as_view(), name='one_enrollment_list'),
    # 报名表添加和编辑
    url(r'^enrollment_add/(?P<customer_id>\d+)$', enrollment.enrollment_change, name='enrollment_add'),
    url(r'^enrollment_add2/$', enrollment.enrollment_change, name='enrollment_add2'),  # 单一添加
    url(r'^enrollment_edit/(?P<pk>\d+)$', enrollment.enrollment_change, name='enrollment_edit'),

    #学习记录


    #班级
    url(r'class/$',teacher.classlist.as_view(),name = 'class_list'),
    url(r'class_edit/(?P<course>\d+)/$',teacher.classchange,name = 'class_edit'),
    url(r'class_add/$',teacher.classchange,name = 'class_add'),


    url(r'course_record/(?P<class_id>\d+)/$',teacher.course_record.as_view(),name = 'course_Record_list'),
    url(r'course_record_add/(?P<class_id>\d+)/$',teacher.course_Record_changes,name = 'course_record_add'),
    url(r'course_record_edit/(\d+)/$',teacher.course_Record_changes,name = 'course_record_edit'),

    url(r'^study_record_list/(?P<course_record_id>\d+)/$', teacher.study_record_list, name='study_record_list'),






    # url(r'paging/',views.paging),
]

crm项目2/crm_poject/crm_poject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app01.urls',namespace='app01'))
]

crm项目2/crm_poject/templates/register_login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>登陆</title>
    {% load static %}
    <link rel="stylesheet" href= "{% static 'css/style.css' %}">
</head>

<body>
<div class="login-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p>Link the world. Share to world.</p>
    </div>
    <form action="" method="post" id="loginForm" novalidate="novalidate">
        {% csrf_token %}
        <div>
            <input type="text" name="username" class="username" placeholder="用户名" autocomplete="off" value="admin">
        </div>
        <div>
            <input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false"
                   onpaste="return false">
        </div>
        <div>{{ error }}</div>
        <button id="submit" type="submit">登 陆</button>
    </form>
    <a href="{% url 'app01:register' %}">
        <button type="button" class="register-tis">还有没有账号？</button>
    </a>
</div>


<script src="{%  static 'js/jquery.min.js' %}"></script>
<script src= "{%  static 'js/common.js' %}"></script>

<script src= "{%  static 'js/supersized.3.2.7.min.js' %}"></script>
<script src= "{%  static 'js/supersized-init.js' %}"></script>

<script src= "{%  static 'js/jquery.validate.min.js' %}"></script>

</body>

</html>

crm项目2/crm_poject/templates/register_login/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>登陆</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        select {
            width: 300px;
            height: 42px;
            line-height: 42px;
            margin-top: 25px;
            padding: 0 15px;
            background: #2d2d2d;
            background: rgba(45, 45, 45, .15);
            -moz-border-radius: 6px;
            -webkit-border-radius: 6px;
            border-radius: 6px;
            border: 1px solid #3d3d3d;
            border: 1px solid rgba(255, 255, 255, .15);
            -moz-box-shadow: 0 2px 3px 0 rgba(0, 0, 0, .1) inset;
            -webkit-box-shadow: 0 2px 3px 0 rgba(0, 0, 0, .1) inset;
            box-shadow: 0 2px 3px 0 rgba(0, 0, 0, .1) inset;
            font-family: microsoft yahei, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #fff;
            text-shadow: 0 1px 2px rgba(0, 0, 0, .1);
            -o-transition: all .2s;
            -moz-transition: all .2s;
            -webkit-transition: all .2s;
            -ms-transition: all .2s;
        }
        option{
            background-color: lightpink;
        }
    </style>
</head>


<body>
<div class="login-container">
    <h1>ShareLink</h1>
    <div class="connect">
        <p>Link the world. Share to world.</p>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ reg_form.username }}
        {{ reg_form.password }}
        {{ reg_form.re_password }}
        {{ reg_form.name }}
        {{ reg_form.department }}
        {{ reg_form.mobile }}
        <button id="submit" type="submit">提 交</button>
    </form>
    <a href="{% url 'app01:login' %}">
        <button type="button" class="register-tis">已有账号？</button>
    </a>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'js/supersized-init.js' %}"></script>

<script src="{% static 'js/jquery.validate.min.js' %}"></script>

</body>

</html>