crm项目2/crm_poject/app01/urls.py
from django.conf.urls import url, include
from app01 import views
from app01.views import base, consultrecord, Customer, enrollment, user,teacher

urlpatterns = [
    # 登陆
    url('login/', user.login, name='login'),
    # 注册
    url('register/', user.register, name='register'),
    # 注册
    url(r'logout/', user.logout, name='logout'),
    # 客户展示
    url(r'index/', Customer.Customer.as_view(), name='index'),
    url(r'my_curtor/', Customer.Customer.as_view(), name='my_curtor'),
    # 客户添加和编辑
    url(r'curtor_add/$', Customer.add, name='curtoradd'),
    url(r'custoredit/(\d+)/', Customer.add, name='custoredit'),
    # 某个销售的跟进记录
    url(r'^consult_record/$', consultrecord.ConsultRecordList.as_view(), name='consult_record'),
    # 某个客户的跟进记录
    url(r'^consult_record/(?P<customer_id>\d+)/$', consultrecord.ConsultRecordList.as_view(),
        name='one_consult_record'),
    # 跟进记录添加和编辑
    url(r'^consult_record_add/$', consultrecord.consult_record_change, name='consult_record_add'),
    url(r'^consult_record_edit/(\d+)/$', consultrecord.consult_record_change, name='consult_record_edit'),
    # 显示报名表
    url(r'^enrollment_list/$', enrollment.EnrollmentList.as_view(), name='enrollment_list'),
    url(r'^enrollment_list/(?P<customer_id>\d+)/$', enrollment.EnrollmentList.as_view(), name='one_enrollment_list'),
    # 报名表添加和编辑
    url(r'^enrollment_add/(?P<customer_id>\d+)$', enrollment.enrollment_change, name='enrollment_add'),
    url(r'^enrollment_add2/$', enrollment.enrollment_change, name='enrollment_add2'),  # 单一添加
    url(r'^enrollment_edit/(?P<pk>\d+)$', enrollment.enrollment_change, name='enrollment_edit'),

    #学习记录


    #班级
    url(r'class/$',teacher.classlist.as_view(),name = 'class_list'),
    url(r'class_edit/(?P<course>\d+)/$',teacher.classchange,name = 'class_edit'),
    url(r'class_add/$',teacher.classchange,name = 'class_add'),


    url(r'course_record/(?P<class_id>\d+)/$',teacher.course_record.as_view(),name = 'course_Record_list'),
    url(r'course_record_add/(?P<class_id>\d+)/$',teacher.course_Record_changes,name = 'course_record_add'),
    url(r'course_record_edit/(\d+)/$',teacher.course_Record_changes,name = 'course_record_edit'),

    url(r'^study_record_list/(?P<course_record_id>\d+)/$', teacher.study_record_list, name='study_record_list'),






    # url(r'paging/',views.paging),
]

crm项目2/crm_poject/crm_poject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app01.urls',namespace='app01'))
]

crm项目2/crm_poject/templates/base_html/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>路飞学城</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }

        .left-menu .menu-body .static-menu {

        }

        .left-menu .menu-body .static-menu .icon-wrap {
            width: 20px;
            display: inline-block;
            text-align: center;
        }

        .left-menu .menu-body .static-menu a {
            text-decoration: none;
            padding: 8px 15px;
            border-bottom: 1px solid #ccc;
            color: #333;
            display: block;
            background: #efefef;
            background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #efefef), color-stop(1, #fafafa));
            background: -ms-linear-gradient(bottom, #efefef, #fafafa);
            background: -o-linear-gradient(bottom, #efefef, #fafafa);
            filter: progid:dximagetransform.microsoft.gradient(startColorStr='#e3e3e3', EndColorStr='#ffffff');
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa',EndColorStr='#efefef')";
            box-shadow: inset 0 1px 1px white;
        }

        .left-menu .menu-body .static-menu a:hover {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        .left-menu .menu-body .static-menu a.active {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        th {
            text-align: center;
        }
    </style>
    {% block css %} {% endblock %}
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/logo.svg' %}">
                <span style="font-size: 18px;">路飞学城 </span>
            </a>
        </div>

        <div class="left-menu left">
            <a class="menu-item">资产管理</a>
            <a class="menu-item">用户信息</a>
            <a class="menu-item">路飞管理</a>
            <div class="menu-item">
                <span>使用说明</span>
                <i class="fa fa-caret-down" aria-hidden="true"></i>
                <div class="more-info">
                    <a href="#" class="more-item">管他什么菜单</a>
                    <a href="#" class="more-item">实在是编不了</a>
                </div>
            </div>
        </div>

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
                    <a href="{% url 'app01:logout' %}" class="more-item">注销</a>
                </div>
            </div>

            <a class="user-menu right">
                消息
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                通知
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                任务
                <i class="fa fa-bell-o" aria-hidden="true"></i>
                <span class="badge bg-danger">4</span>
            </a>
        </div>

    </div>
</div>
<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            <div class="static-menu">
                <a href="{% url 'app01:index' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span>客户库</a>
                <a href="{% url 'app01:my_curtor' %}"><span class="icon-wrap"><i class="fa fa-map-o"
                                                                                 aria-hidden="true"></i></span>我的客户</a>
                <a href="{% url 'app01:consult_record' %}"><span class="icon-wrap"><i class="fa fa-map-o"
                                                                                      aria-hidden="true"></i></span>跟进信息</a>
                <a href="{% url 'app01:enrollment_list' %}"><span class="icon-wrap"><i class="fa fa-map-o"
                                                                                 aria-hidden="true"></i></span>
                    报名记录</a>
                <a href="{% url 'app01:class_list' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span>
                    班级列表</a>
            </div>
        </div>
    </div>
    <div class="right-body">
        <div>
            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

                <li><a href="#">首页</a></li>
                <li class="active">客户管理</li>

            </ol>
        </div>
        {% block content %}

        {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
{% block js %} {% endblock %}
</body>
</html>