crm项目2/crm_poject/app01/urls.py
from django.conf.urls import url, include
from app01 import views
from app01.views import base, consultrecord, Customer, enrollment, user,teacher

urlpatterns = [
    # 登陆
    url('login/', user.login, name='login'),
    # 注册
    url('register/', user.register, name='register'),
    # 注册
    url(r'logout/', user.logout, name='logout'),
    # 客户展示
    url(r'index/', Customer.Customer.as_view(), name='index'),
    url(r'my_curtor/', Customer.Customer.as_view(), name='my_curtor'),
    # 客户添加和编辑
    url(r'curtor_add/$', Customer.add, name='curtoradd'),
    url(r'custoredit/(\d+)/', Customer.add, name='custoredit'),
    # 某个销售的跟进记录
    url(r'^consult_record/$', consultrecord.ConsultRecordList.as_view(), name='consult_record'),
    # 某个客户的跟进记录
    url(r'^consult_record/(?P<customer_id>\d+)/$', consultrecord.ConsultRecordList.as_view(),
        name='one_consult_record'),
    # 跟进记录添加和编辑
    url(r'^consult_record_add/$', consultrecord.consult_record_change, name='consult_record_add'),
    url(r'^consult_record_edit/(\d+)/$', consultrecord.consult_record_change, name='consult_record_edit'),
    # 显示报名表
    url(r'^enrollment_list/$', enrollment.EnrollmentList.as_view(), name='enrollment_list'),
    url(r'^enrollment_list/(?P<customer_id>\d+)/$', enrollment.EnrollmentList.as_view(), name='one_enrollment_list'),
    # 报名表添加和编辑
    url(r'^enrollment_add/(?P<customer_id>\d+)$', enrollment.enrollment_change, name='enrollment_add'),
    url(r'^enrollment_add2/$', enrollment.enrollment_change, name='enrollment_add2'),  # 单一添加
    url(r'^enrollment_edit/(?P<pk>\d+)$', enrollment.enrollment_change, name='enrollment_edit'),

    #学习记录


    #班级
    url(r'class/$',teacher.classlist.as_view(),name = 'class_list'),
    url(r'class_edit/(?P<course>\d+)/$',teacher.classchange,name = 'class_edit'),
    url(r'class_add/$',teacher.classchange,name = 'class_add'),


    url(r'course_record/(?P<class_id>\d+)/$',teacher.course_record.as_view(),name = 'course_Record_list'),
    url(r'course_record_add/(?P<class_id>\d+)/$',teacher.course_Record_changes,name = 'course_record_add'),
    url(r'course_record_edit/(\d+)/$',teacher.course_Record_changes,name = 'course_record_edit'),

    url(r'^study_record_list/(?P<course_record_id>\d+)/$', teacher.study_record_list, name='study_record_list'),






    # url(r'paging/',views.paging),
]

crm项目2/crm_poject/crm_poject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app01.urls',namespace='app01'))
]

crm项目2/crm_poject/app01/models.py
from django.db import models
from multiselectfield import MultiSelectField

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)

pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return  self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)
    def __str__(self):
        return self.qq

    def show_class_list(self):
        return ",".join([str(i) for i in self.class_list.all()])

    def show_color_statuc(self):
        color_dic = {
            'signed': "blue",
            'unregistered': "red",
            'studying': 'green',
            'paid_in_full': 'yellow',
        }
        return '<span style="background-color: {};padding: 6px">{}</span>'.format(color_dic[self.status],
                                                                                  self.get_status_display())


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')


    def __str__(self):
        st = str(self.campuses) + self.get_course_display() + str(self.semester) + "期"
        return st

    def show_teachers(self):
        return ",".join([str(i)  for i in self.teachers.all()])


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses',verbose_name='学校')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师", related_name='Course_Record')
    recorder = models.ForeignKey('UserProfile', verbose_name="记录者", related_name='CourseRecord')

    class Meta:
        unique_together = ('re_class', 'day_num')


class StudyRecord(models.Model):
    """
    学习记录
    """

    attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)

crm项目2/crm_poject/templates/class_list/class_list.html
{% extends 'base_html/layout.html' %}
{% load my_tags %}
{% block css %}
    <style>
        #filtertxt1 {
            padding-left: 10px;
            padding-right: 10px;
            width: 330px;
            height: 39px;
            border: 1px solid #394c62;
            border-radius: 20px;
        }

        .sousuo {
            width: 98px;
            height: 39px;
            border-radius: 19px;
            border: none;
            font-size: 16px;
            background: #486d90;
            color: #fff;
        }

        button {
            text-align: center;
        }

        .button {
            border: 1px solid rgba(0, 0, 0, 0.4);
            box-shadow: inset 0 1px 0 0 rgba(255, 255, 255, 0.5), 0 0 1px 1px rgba(255, 255, 255, 0.8), 0 0 0 6px rgba(0, 0, 0, 0.06), 0 0 0 3px rgba(0, 0, 0, 0.1);
        }

        .title {
            padding: 10px;
            float: left;
            color: #fff;
            font-weight: 800;
            font-size: 20px;
            text-shadow: 1px 1px rgba(0, 0, 0, 0.2);
            text-transform: uppercase;
            border-right: 1px solid rgba(255, 255, 255, 0.3);
            border-radius: 19px;
        }

        .price {
            padding: 10px;
            float: left;
            color: rgba(0, 0, 0, 0.4);
            font-weight: 800;
            font-size: 20px;
            text-shadow: 1px 1px rgba(255, 255, 255, 0.3);
            text-transform: uppercase;
            border-left: 1px solid rgba(0, 0, 0, 0.2);
        }
    </style>
{% endblock %}
{% block content %}
    <div>
        <form action="" class="pull-right">
            {% csrf_token %}
            <select class="form-control" name="query_field">
                <option value="name">姓名</option>
                <option value="phone"> 手机号</option>
                <option value="qq">qq</option>
            </select>
            <input type="text" id="filtertxt1" name='query' value="{{ sousuo }}">
            <button class="btn btn-primary sousuo"> 搜索 <i class="fa fa-search " aria-hidden="true"></i></button>
        </form>
    </div>
    <a href="{% reverse_url request 'app01:class_add' %}">
        <button>新增<i class="fa fa-plus"></i></button>
    </a>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <select name="action" class="form-control">
        </select>
        <button type="submit">提交</button>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选项</th>
                <th>序号</th>
                <th>班级名称</th>
                <th>学费</th>
                <th>开班日期</th>
                <th>结业日期</th>
                <th>老师</th>
                <th>班级类型</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody style="text-align: center">

                {% for all_class in all_classes %}

                <tr>
                    <td><input name="optionses" value="{{ all_class.pk }}" type="checkbox"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ all_class }}</td>
                    <td>{{ all_class.price }}</td>
                    <td>{{ all_class.start_date }}</td>
                    <td>{{ all_class.graduate_date }}</td>
                    <td>{{ all_class.show_teachers }}</td>
                    <td>{{ all_class.get_class_type_display }}</td>
                    <td>
                        <a class="btn btn-primary"
                           href="{% reverse_url request 'app01:class_edit' all_class.pk %}">编辑 <i
                                class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        <a class="btn btn-success btn-sm"
                           href="{% reverse_url request 'app01:course_Record_list' all_class.pk %}">课程记录</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </form>
    {% if all_classes %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_obj.page_html }}
            </ul>
        </nav>
    {% endif %}

{% endblock %}

crm项目2/crm_poject/templates/class_list/courserecord_list.html
{% extends 'base_html/layout.html' %}
{% load my_tags %}
{% block css %}
    <style>
        #filtertxt1 {
            padding-left: 10px;
            padding-right: 10px;
            width: 330px;
            height: 39px;
            border: 1px solid #394c62;
            border-radius: 20px;
        }

        .sousuo {
            width: 98px;
            height: 39px;
            border-radius: 19px;
            border: none;
            font-size: 16px;
            background: #486d90;
            color: #fff;
        }

        button {
            text-align: center;
        }

        .button {
            border: 1px solid rgba(0, 0, 0, 0.4);
            box-shadow: inset 0 1px 0 0 rgba(255, 255, 255, 0.5), 0 0 1px 1px rgba(255, 255, 255, 0.8), 0 0 0 6px rgba(0, 0, 0, 0.06), 0 0 0 3px rgba(0, 0, 0, 0.1);
        }

        .title {
            padding: 10px;
            float: left;
            color: #fff;
            font-weight: 800;
            font-size: 20px;
            text-shadow: 1px 1px rgba(0, 0, 0, 0.2);
            text-transform: uppercase;
            border-right: 1px solid rgba(255, 255, 255, 0.3);
            border-radius: 19px;
        }

        .price {
            padding: 10px;
            float: left;
            color: rgba(0, 0, 0, 0.4);
            font-weight: 800;
            font-size: 20px;
            text-shadow: 1px 1px rgba(255, 255, 255, 0.3);
            text-transform: uppercase;
            border-left: 1px solid rgba(0, 0, 0, 0.2);
        }
    </style>
{% endblock %}
{% block content %}
    <div>
        <form action="" class="pull-right">
            {% csrf_token %}
            <select class="form-control" name="query_field">
                <option value="name">姓名</option>
                <option value="phone"> 手机号</option>
                <option value="qq">qq</option>
            </select>
            <input type="text" id="filtertxt1" name='query' value="{{ sousuo }}">
            <button class="btn btn-primary sousuo"> 搜索 <i class="fa fa-search " aria-hidden="true"></i></button>
        </form>
    </div>
    <a href="{% reverse_url request 'app01:course_record_add' class_id %}">
        <button>新增<i class="fa fa-plus"></i></button>
    </a>

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <select name="action" class="form-control">
            <option value="multi_init">批量添加学习记录</option>
        </select>
        <button type="submit">提交</button>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选项</th>
                <th>序号</th>
                <th>课程名称</th>
                <th>标题</th>
                <th>是否有作业</th>
                <th>作业标题</th>
                <th>讲师</th>
                <th>记录者</th>
                <th>日期</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody style="text-align: center">

            {% for foo in all_courserecord %}

                <tr>
                    <td><input name="pk" value="{{ foo.pk }}" type="checkbox"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ foo.course }}</td>
                    <td>{{ foo.course_title }}</td>
                    <td>
                        {% if foo.has_homework %}
                            是
                        {% else %}
                            否
                        {% endif %}
                    </td>
                    <td>{{ foo.homework_title }}</td>
                    <td>{{ foo.teacher }}</td>
                    <td>{{ foo.recorder }}</td>
                    <td>{{ foo.date }}</td>
                    <td>
                        <a class="btn btn-primary"
                           href="{% reverse_url request 'app01:course_record_edit' foo.pk %}">编辑 <i
                                class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        <a class="btn btn-success btn-sm"
                           href="{% url 'app01:study_record_list' foo.pk %}">查看学习记录</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </form>
    {% if all_courserecord %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_obj.page_html }}
            </ul>
        </nav>
    {% endif %}

{% endblock %}

crm项目2/crm_poject/templates/class_list/study_record_list.html
{% extends 'base_html/layout.html' %}
{% load my_tags %}
{% block css %}
    <style>
        #filtertxt1 {
            padding-left: 10px;
            padding-right: 10px;
            width: 330px;
            height: 39px;
            border: 1px solid #394c62;
            border-radius: 20px;
        }

        .sousuo {
            width: 98px;
            height: 39px;
            border-radius: 19px;
            border: none;
            font-size: 16px;
            background: #486d90;
            color: #fff;
        }

        button {
            text-align: center;
        }

        .button {
            border: 1px solid rgba(0, 0, 0, 0.4);
            box-shadow: inset 0 1px 0 0 rgba(255, 255, 255, 0.5), 0 0 1px 1px rgba(255, 255, 255, 0.8), 0 0 0 6px rgba(0, 0, 0, 0.06), 0 0 0 3px rgba(0, 0, 0, 0.1);
        }

        .title {
            padding: 10px;
            float: left;
            color: #fff;
            font-weight: 800;
            font-size: 20px;
            text-shadow: 1px 1px rgba(0, 0, 0, 0.2);
            text-transform: uppercase;
            border-right: 1px solid rgba(255, 255, 255, 0.3);
            border-radius: 19px;
        }

        .price {
            padding: 10px;
            float: left;
            color: rgba(0, 0, 0, 0.4);
            font-weight: 800;
            font-size: 20px;
            text-shadow: 1px 1px rgba(255, 255, 255, 0.3);
            text-transform: uppercase;
            border-left: 1px solid rgba(0, 0, 0, 0.2);
        }
    </style>
{% endblock %}
{% block content %}

    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选项</th>
                <th>序号</th>
                <th>学生</th>
                <th>考勤</th>
                <th>成绩</th>
                <th>评语</th>
            </tr>
            </thead>
            <tbody style="text-align: center">

            {% for foo in form_set %}
                <tr>
                    <td><input name="optionses" value="{{ foo.pk }}" type="checkbox"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ foo.student }}</td>
                    <td>{{ foo.attendance }}</td>
                    <td>{{ foo.score }}</td>
                    <td>{{ foo.homework_note }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
      <button type="submit" class="btn  btn-success">保存</button>

    </form>
    {% if form_set %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_obj.page_html }}
            </ul>
        </nav>
    {% endif %}

{% endblock %}